import type { ParseOutput } from "./parser.ts"

const JS_TEMPLATE = `// GENERATED BY querypack. DO NOT MODIFY THIS.

const __unescape = (text) => Buffer.from(text, "base64").toString()
\n`

const TS_TEMPLATE = `// GENERATED BY querypack. DO NOT MODIFY THIS.

declare global {
  namespace QueryPack {
    interface DbClient {
      one(text: string, params: any): Promise<any>
      many(text: string, params: any): Promise<any>
      exec(text: string, params: any): Promise<ExecOutput>
      execresult(text: string, params: any): Promise<ExecResultOutput>
    }

    interface ExecOutput {
      affectedRows: number
    }

    interface ExecResultOutput {
      insertId: number
    }
  }
}
\n`

export function generator(queries: { name: string; parsed: ParseOutput }[]) {
  const dts: string[] = []
  const js: string[] = []

  for (const q of queries) {
    const { parsed } = q
    const name = parsed.name

    const queryConstName = `${name}_Query`
    const paramsName = `${name}_Params`
    const dataRowName = `${name}_DataRow`

    const queryConstDecl = `export const ${queryConstName}: string`
    const queryConstDef = `export const ${queryConstName} = __unescape(\`${escape(parsed.text)}\`)`

    const paramsDecl = `export interface ${paramsName} {
  ${parsed.params.map(param => `${param.name}: ${param.type}`).join("\n  ")}
}`

    const dataRowDecl = `export interface ${dataRowName} {
  ${parsed.fields.map(field => `${field.name}: ${field.type}`).join("\n  ")}
}`

    dts.push(queryConstDecl, paramsDecl, dataRowDecl)
    js.push(queryConstDef)

    switch (parsed.mode) {
      case "noemit": break
      case "one":
      case "many": {
        const selectFnName = name
        const decodeRowFnName = `${name}_decodeRow`

        const decodeRowFnDecl = `export function ${decodeRowFnName}(row: any): ${dataRowName}`
        const decodeRowFnDef = `export function ${decodeRowFnName}(row) {
  return {
    ${parsed.fields.map(field => `${field.name}: ${decodeExpr(`row.${field.name}`, field.type)}`).join(",\n    ")}
  }
}`

        const selectFnDecl = parsed.mode === "one"
          ? `export function ${selectFnName}(client: QueryPack.DbClient, params?: ${paramsName}): Promise<${dataRowName}>`
          : `export function ${selectFnName}(client: QueryPack.DbClient, params?: ${paramsName}): Promise<${dataRowName}[]>`

        const selectFnDef = parsed.mode === "one"
          ? `export async function ${selectFnName}(client, params) {
  return ${decodeRowFnName}(await client.one(${queryConstName}, params))
}`
          : `export async function ${selectFnName}(client, params) {
  return (await client.many(${queryConstName}, params)).map(${decodeRowFnName})
}`

        dts.push(decodeRowFnDecl, selectFnDecl)
        js.push(decodeRowFnDef, selectFnDef)
        break
      }
      case "exec": {
        const fnName = name

        const execFnDecl = `export function ${fnName}(client: QueryPack.DbClient, params?: ${paramsName}): Promise<QueryPack.ExecOutput>`
        const execFnDef = `export async function ${fnName}(client, params) {
  return await client.exec(${queryConstName}, params)
}`
        dts.push(execFnDecl)
        js.push(execFnDef)
        break
      }
      case "execresult": {
        const fnName = name

        const execFnDecl = `export function ${fnName}(client: QueryPack.DbClient, params?: ${paramsName}): Promise<QueryPack.ExecResultOutput>`
        const execFnDef = `export async function ${fnName}(client, params) {
  return await client.execresult(${queryConstName}, params)
}`
        dts.push(execFnDecl)
        js.push(execFnDef)
        break
      }
      default: throw new Error("unrecognized mode", { cause: { mode: parsed.mode } })
    }
  }

  const dtsCode = `${TS_TEMPLATE}${dts.join("\n\n")}\n`
  const jsCode = `${JS_TEMPLATE}${js.join("\n\n")}\n`
  return { dts: dtsCode, js: jsCode }
}

// TODO: better way
function decodeExpr(s: string, type: string) {
  function decode(s: string, type: string): string {
    type = type.trim()

    // (T) => T
    if (type.startsWith("(") && type.endsWith(")")) {
      return decode(s, type.slice(1, type.length - 1))
    }

    // T | null
    // s && decode(s, T)
    if (type.endsWith("| null")) {
      const nonNullType = type.slice(0, type.length - 6)
      return `${s} && ${decode(s, nonNullType)}`
    }

    switch (type) {
      case "boolean": return `!!${s}`
      case "bigint": return `BigInt(${s})`
      default: return s
    }
  }
  return decode(s, type)
}

function escape(text: string) {
  return Buffer.from(text).toString("base64")
}

// for testing
export function stripTemplate(output: string) {
  return output.startsWith(JS_TEMPLATE) ? output.slice(JS_TEMPLATE.length) :
    output.startsWith(TS_TEMPLATE) ? output.slice(TS_TEMPLATE.length) :
      output
}
